const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"博客类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBoke"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"房屋类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFangwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"房屋朝向管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFangwuChaoxiang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"房屋投诉类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFangwuTousu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"商家信用类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShangjiaXingji"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"博客管理",
                        "menuJump":"列表",
                        "tableName":"boke"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"博客留言管理",
                        "menuJump":"列表",
                        "tableName":"bokeLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"博客收藏管理",
                        "menuJump":"列表",
                        "tableName":"bokeCollection"
                    }
                ],
                "menu":"博客管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"房屋管理",
                        "menuJump":"列表",
                        "tableName":"fangwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"房屋留言管理",
                        "menuJump":"列表",
                        "tableName":"fangwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"房屋收藏管理",
                        "menuJump":"列表",
                        "tableName":"fangwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"预约看房管理",
                        "menuJump":"列表",
                        "tableName":"fangwuOrder"
                    }
                ],
                "menu":"房屋管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"房屋投诉管理",
                        "menuJump":"列表",
                        "tableName":"fangwuTousu"
                    }
                ],
                "menu":"房屋投诉管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商家管理",
                        "menuJump":"列表",
                        "tableName":"shangjia"
                    }
                ],
                "menu":"商家管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"博客管理",
                        "menuJump":"列表",
                        "tableName":"boke"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"博客留言管理",
                        "menuJump":"列表",
                        "tableName":"bokeLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"博客收藏管理",
                        "menuJump":"列表",
                        "tableName":"bokeCollection"
                    }
                ],
                "menu":"博客管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"房屋留言管理",
                        "menuJump":"列表",
                        "tableName":"fangwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"房屋收藏管理",
                        "menuJump":"列表",
                        "tableName":"fangwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"预约看房管理",
                        "menuJump":"列表",
                        "tableName":"fangwuOrder"
                    }
                ],
                "menu":"房屋管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"房屋投诉管理",
                        "menuJump":"列表",
                        "tableName":"fangwuTousu"
                    }
                ],
                "menu":"房屋投诉管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"房屋管理",
                        "menuJump":"列表",
                        "tableName":"fangwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"房屋留言管理",
                        "menuJump":"列表",
                        "tableName":"fangwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "审核",
                            "查看"
                        ],
                        "menu":"预约看房管理",
                        "menuJump":"列表",
                        "tableName":"fangwuOrder"
                    }
                ],
                "menu":"房屋管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"商家",
        "tableName":"shangjia"
    }
]
    }
}
export default menu;
